## CONFIGURACIÓN LOCAL DE SSH
#
# Tipo de llave pública
HostKey /etc/ssh/ssh_host_ed25519_key
# Registrar intentos fallidos
LogLevel VERBOSE
#
# Permitir el acceso a root
PermitRootLogin no
StrictModes yes
#
# Permitir la llave pública
PubkeyAuthentication yes
#
# Permitir identificar con usuario y contraseñas
PasswordAuthentication yes
#
# Permitir contraseñas en blanco
PermitEmptyPasswords no
#
# Deshabilitar reenvío X11 si no es necesario
X11Forwarding no
# Link de Banner del servidor
Banner /etc/ssh/banner