## CONFIGURACIÓN LOCAL DE SSH
#
# Tipo de llave pública
HostKey /etc/ssh/ssh_host_ed25519_key
# Registrar intentos fallidos
LogLevel VERBOSE
#
# Permitir el acceso a root
PermitRootLogin no
StrictModes yes
#
# Identificacion de Cliente con preguntas
KbdInteractiveAuthentication no
#
# Permitir la llave pública
PubkeyAuthentication yes
#
# Permitir identificar con usuario y contraseñas
PasswordAuthentication yes
#
# Forzar solo algoritmos modernos
HostKeyAlgorithms ssh-ed25519,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256
PubkeyAcceptedAlgorithms ssh-ed25519,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256
# Permitir contraseñas en blanco
PermitEmptyPasswords no
#
# Deshabilitar reenvío X11 si no es necesario
X11Forwarding no
# Permite SSH para transferir archivos (SFTP)
PermitTTY yes
# Mensaje de bienvenida del sistema
PrintMotd yes
# Muestra Fecha y hora ultimo acceso.
PrintLastLog yes
# Mensaje de conexion sigue viva.
TCPKeepAlive yes
# Link de Banner del servidor
Banner /etc/ssh/banner