[global]
#Permitir acceso a versiones de samba
client min protocol = NT1
client max protocol = SMB3
server min protocol = SMB3
# 
# Browsing / Identificacion

#Carpeta Compartida /tmp
[SAMBA]
   comment = Carpeta-Compartida
   path = /tmp/samba
   guest ok = yes
   force user = nobody  
   force group = nogroup   
   browseable = yes
   writeable = yes
   create mask = 0700
   directory mask = 0700