[global]
#Permitir acceso a versiones de samba
client min protocol = SMB3
client max protocol = SMB3
server min protocol = SMB3
server max protocol = SMB3
# 
# Browsing / Identificacion

#Carpeta compartida de acceso autenticado
[SAMBA]
   comment = Carpeta-Compartida
   path = /tmp/directorio-samba
   guest ok = no
   valid users = Carpeta
   browseable = yes
   read only = no
   create mask = 0600
   directory mask = 0700