# SSH servers
#
[sshd]
#backend = systemd
journalmatch = _SYSTEMD_UNIT=ssh.service + _COMM=sshd
enabled = true
port    = ssh
protocol = tcp
#
# Ban IP Reportes SSH a AbuseIPDB
#action = %(action_)s
#         %(action_abuseipdb)s